apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
spec:
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: yaowl/neo-ui-deploy:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gui
spec:
  type: NodePort
  selector:
    app: gui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32260